### ISSUE TITLE
How to use binary release

### ISSUE THREAD

**Issue by kBoltz** [BentonEdmondson/knock#1]
I want to try knock out, but after downloading the knock-0.0.0-x86_64-linux file, I am unsure what to do with it. Could you help?

I am on Ubuntu 20.04 if that helps.

**Comment by BentonEdmondson** [comment]
Assuming `knock-0.0.0-x86_64-linux` is in the folder `~/Downloads` and the ACSM file is located at `~/Documents/my-book.acsm` then do the following:

1. Create a free Adobe account [here](https://account.adobe.com) if you do not already have one
1. Open a terminal and run `~/Downloads/knock-0.0.0-x86_64-linux ~/Documents/my-book.acsm`
1. Enter in your Adobe email and password when prompted

`~/Documents/my-book.epub` should then be created. If you need more detail I can clarify.

**Comment by noideawhatiamtalkingabout** [comment]
i followed this instructions

./knock ~/Downloads/s2.acsm 
chmod: Beim Setzen der Zugriffsrechte für './run': Die Operation ist nicht erlaubt
translation: operation not allowed during setting access rights for ./run

sudo ./knock ~/Downloads/s2.acsm
Traceback (most recent call last):
  File "/nix/store/f6m60ymgfh2clcqc3fz5s7kqla4c23xv-knock-0.0.0/bin/.knock-wrapped", line 18, in <module>
    if not args.acsm_file.exists():
  File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/pathlib.py", line 1400, in exists
    self.stat()
  File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/pathlib.py", line 1197, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/home/u/Downloads/s2.acsm'

ls -l /home/u/Downloads/s2.acsm 
-rw-rw-rw- 1 u u 1177 26. Jul 19:19 /home/u/Downloads/s2.acsm

Linux nb 5.12.19-1-MANJARO #1 SMP PREEMPT Tue Jul 20 20:57:37 UTC 2021 x86_64 GNU/Linux

**Comment by BentonEdmondson** [comment]
@noideawhatiamtalkingabout show me `ls -l ./knock` and make sure you don't have `s2.acsm` open in another program.

**Comment by noideawhatiamtalkingabout** [comment]
`ls -l knock`
-rwxrwxrwx 1 u u 116084331 26. Jul 19:10 knock

... and i even downloaded the acsm again..

**Comment by BentonEdmondson** [comment]
Can you temporarily change your system to English and then run `./knock ~/Downloads/s2.acsm` so I can get the precise error message?

**Comment by noideawhatiamtalkingabout** [comment]
did that. came a bit further simply by changes to english. so first knock seems not to work with another language set.

`./knock /home/u/Downloads/ss.acsm` 
This device is not registered with Adobe.
Enter your Adobe account's email address: xxx@xxx.com     
Enter your Adobe account's password: 
Registering this device with Adobe...
Downloading the ACSM file from Adobe...
Decrypting the file...
Traceback (most recent call last):
  File "/nix/store/zpjmnj7d18h6y1ylx541fb0abj9f4gb7-inept-epub-7.0/bin/inept-epub", line 429, in <module>
    sys.exit(cli_main())
  File "/nix/store/zpjmnj7d18h6y1ylx541fb0abj9f4gb7-inept-epub-7.0/bin/inept-epub", line 423, in cli_main
    result = decryptBook(userkey, inpath, outpath)
  File "/nix/store/zpjmnj7d18h6y1ylx541fb0abj9f4gb7-inept-epub-7.0/bin/inept-epub", line 337, in decryptBook
    with closing(ZipFile(open(inpath, 'rb'))) as inf:
  File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Traceback (most recent call last):
  File "/nix/store/f6m60ymgfh2clcqc3fz5s7kqla4c23xv-knock-0.0.0/bin/.knock-wrapped", line 50, in <module>
    subprocess.check_output([
  File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['inept-epub', '/home/u/.config/knock/activation.xml', '/home/u/Downloads/ss.drm.epub', '/home/u/Downloads/ss.epub']' returned non-zero exit status 1.

**Comment by noideawhatiamtalkingabout** [comment]
ps just tried to open the mentioned epub file in calibre:

calibre, version 5.23.0
FEHLER: Buch konnte nicht geladen werden: Buch konnte nicht geöffnet werden: /home/u/Calibre-Bibliothek/Unbekannt/ss.drm (3)/ss.drm - Unbekannt.epub. "Details anzeigen" anklicken für weitere Informationen.

Failed to convert book: /home/u/Calibre-Bibliothek/Unbekannt/ss.drm (3)/ss.drm - Unbekannt.epub with error:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/ebooks/metadata/epub.py", line 161, in get_zip_reader
    zf = ZipFile(stream, mode='r')
  File "/usr/lib/calibre/calibre/utils/zipfile.py", line 775, in __init__
    self._GetContents()
  File "/usr/lib/calibre/calibre/utils/zipfile.py", line 810, in _GetContents
    self._RealGetContents()
  File "/usr/lib/calibre/calibre/utils/zipfile.py", line 825, in _RealGetContents
    raise BadZipfile("File is not a zip file")
calibre.utils.zipfile.BadZipfile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 433, in get_file_type_metadata
    mi = plugin.get_metadata(stream, ftype.lower().strip())
  File "/usr/lib/calibre/calibre/customize/builtins.py", line 198, in get_metadata
    return get_quick_metadata(stream)
  File "/usr/lib/calibre/calibre/ebooks/metadata/epub.py", line 238, in get_quick_metadata
    return get_metadata(stream, False)
  File "/usr/lib/calibre/calibre/ebooks/metadata/epub.py", line 217, in get_metadata
    reader = get_zip_reader(stream)
  File "/usr/lib/calibre/calibre/ebooks/metadata/epub.py", line 164, in get_zip_reader
    zf = LocalZipFile(stream)
  File "/usr/lib/calibre/calibre/utils/localunzip.py", line 264, in __init__
    _extractall(stream, file_info=self.file_info)
  File "/usr/lib/calibre/calibre/utils/localunzip.py", line 240, in _extractall
    raise ValueError('Not a ZIP file')
ValueError: Not a ZIP file
DeDRM v7.2.1: Trying to decrypt ss.drm - Unbekannt.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Error 'File is not a zip file' when checking zip archive
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 210, in ePubDecrypt
    fr = zipfix.fixZip(path_to_ebook, inf.name)
  File "calibre_plugins.dedrm.zipfix", line 53, in __init__
    self.inzip = zipfilerugged.ZipFile(zinput,'r')
  File "/tmp/calibre_5.23.0_tmp_memnaoqg/y1t2hephplugin_unzip/zipfilerugged.py", line 683, in __init__
    self._GetContents()
  File "/tmp/calibre_5.23.0_tmp_memnaoqg/y1t2hephplugin_unzip/zipfilerugged.py", line 709, in _GetContents
    self._RealGetContents()
  File "/tmp/calibre_5.23.0_tmp_memnaoqg/y1t2hephplugin_unzip/zipfilerugged.py", line 721, in _RealGetContents
    raise BadZipfile("File is not a zip file")
zipfilerugged.BadZipfile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 176, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 644, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 214, in ePubDecrypt
    raise Exception(e)
Exception: File is not a zip file
InputFormatPlugin: EPUB Input running
on /home/u/Calibre-Bibliothek/Unbekannt/ss.drm (3)/ss.drm - Unbekannt.epub
EPUB appears to be invalid ZIP file, trying a more forgiving ZIP parser
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/epub_input.py", line 262, in convert
    zf = ZipFile(stream)
  File "/usr/lib/calibre/calibre/utils/zipfile.py", line 775, in __init__
    self._GetContents()
  File "/usr/lib/calibre/calibre/utils/zipfile.py", line 810, in _GetContents
    self._RealGetContents()
  File "/usr/lib/calibre/calibre/utils/zipfile.py", line 825, in _RealGetContents
    raise BadZipfile("File is not a zip file")
calibre.utils.zipfile.BadZipfile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/calibre-parallel", line 21, in <module>
    sys.exit(main())
  File "/usr/lib/calibre/calibre/utils/ipc/worker.py", line 197, in main
    exec(sys.argv[-1])
  File "<string>", line 1, in <module>
  File "/usr/lib/calibre/calibre/srv/render_book.py", line 824, in viewer_main
    render_for_viewer(*args)
  File "/usr/lib/calibre/calibre/srv/render_book.py", line 815, in render_for_viewer
    return render(
  File "/usr/lib/calibre/calibre/srv/render_book.py", line 792, in render
    book_fmt, opfpath, input_fmt = extract_book(pathtoebook, output_dir, log=default_log)
  File "/usr/lib/calibre/calibre/ebooks/oeb/iterator/book.py", line 63, in extract_book
    pathtoopf = plumber.input_plugin(inf,
  File "/usr/lib/calibre/calibre/customize/conversion.py", line 245, in __call__
    ret = self.convert(stream, options, file_ext,
  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/epub_input.py", line 269, in convert
    extractall(stream)
  File "/usr/lib/calibre/calibre/utils/localunzip.py", line 253, in extractall
    _extractall(f, path)
  File "/usr/lib/calibre/calibre/utils/localunzip.py", line 240, in _extractall
    raise ValueError('Not a ZIP file')
ValueError: Not a ZIP file

**Comment by BentonEdmondson** [comment]
Ah! I think I know the problem. Did you get an EPUB file or a PDF? This only works on EPUBs, but I can add PDF support in the future if needed.

**Comment by noideawhatiamtalkingabout** [comment]
from my purchase i got a .aacsm file - and .knock left a .drm.epub file 

`file -b s2.drm.epub`
PDF document, version 1.4

and i cannot open it - as it requires a password 

any idea/short time workaround?

**Comment by BentonEdmondson** [comment]
Yeah I have a couple of ideas. Please open another issue for PDFs and then another for non-English language set if that still doesn't work

**Comment by BentonEdmondson** [comment]
@kBoltz any luck?

**Comment by kBoltz** [comment]
Not really. It tells me

```
$ ./knock-0.0.0-x86_64-linux Beginner_s_Guide_to_SOLIDWORKS_2016_Leve-pdf.acsm 
Traceback (most recent call last):
  File "/nix/store/f6m60ymgfh2clcqc3fz5s7kqla4c23xv-knock-0.0.0/bin/.knock-wrapped", line 19, in <module>
    raise Exception(f'{str(args.acsm_file)} does not exist.')
Exception: Beginner_s_Guide_to_SOLIDWORKS_2016_Leve-pdf.acsm does not exist.
```
I was then re-reading the README and noted how you mention that this works for books from ebooks.com. I bought mine from play.google.com

**Comment by BentonEdmondson** [comment]
First update to the newest release. Then, make sure you are providing the path to the ACSM file. For example if it is in your downloads folder, run `./knock ~/Downloads/Beginner_s_Guide_to_SOLIDWORKS.acsm`

**Comment by BentonEdmondson** [comment]
@kBoltz working?

**Comment by BentonEdmondson** [comment]
Closing based on https://github.com/BentonEdmondson/knock/issues/6 and unresponsiveness. Feel free to reopen
