### ISSUE TITLE
Breaks on non-English system

### ISSUE THREAD

**Issue by noideawhatiamtalkingabout** [BentonEdmondson/knock#2]
./knock ~/Downloads/s2.acsm
chmod: Beim Setzen der Zugriffsrechte für './run': Die Operation ist nicht erlaubt
translation: operation not allowed during setting access rights for ./run

sudo ./knock ~/Downloads/s2.acsm
Traceback (most recent call last):
File "/nix/store/f6m60ymgfh2clcqc3fz5s7kqla4c23xv-knock-0.0.0/bin/.knock-wrapped", line 18, in
if not args.acsm_file.exists():
File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/pathlib.py", line 1400, in exists
self.stat()
File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/pathlib.py", line 1197, in stat
return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/home/u/Downloads/s2.acsm'

ls -l /home/u/Downloads/s2.acsm
-rw-rw-rw- 1 u u 1177 26. Jul 19:19 /home/u/Downloads/s2.acsm

Linux nb 5.12.19-1-MANJARO #1 SMP PREEMPT Tue Jul 20 20:57:37 UTC 2021 x86_64 GNU/Linux

**Comment by BentonEdmondson** [comment]
[Here](https://github.com/BentonEdmondson/knock/issues/1#issuecomment-886971390) we found that changing to English fixed this problem. I'll have to think about this, I don't know what it could be right now

**Comment by BentonEdmondson** [comment]
My plan here is to attempt to bundle it as an AppImage

**Comment by BentonEdmondson** [comment]
@noideawhatiamtalkingabout see if the new release works

**Comment by noideawhatiamtalkingabout** [comment]
@BentonEdmondson 
this is how it look with the latest release on english system:

`./knock /home/u/Downloads/s.acsm `
Traceback (most recent call last):
  File "/nix/store/q0radzyxb5i9c6ayqqflwijlk2n12p67-knock-0.0.1/bin/.knock-wrapped", line 17, in <module>
    if not args.acsm_file.exists():
  File "/nix/store/yqjhkdarf7p74wcha7aypzsb751n7wl2-python3-3.9.5/lib/python3.9/pathlib.py", line 1414, in exists
    self.stat()
  File "/nix/store/yqjhkdarf7p74wcha7aypzsb751n7wl2-python3-3.9.5/lib/python3.9/pathlib.py", line 1222, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/home/u/Downloads/s.acsm'

**Comment by BentonEdmondson** [comment]
@noideawhatiamtalkingabout try running `run echo "kernel.unprivileged_userns_clone=1" >> /etc/sysctl.conf` and rebooting to enable user namespaces

**Comment by BentonEdmondson** [comment]
@noideawhatiamtalkingabout does this do the trick?

**Comment by noideawhatiamtalkingabout** [comment]
Won’t have time to follow up on this

**Comment by BentonEdmondson** [comment]
Alright, anyone feel free to reopen if you get this issue

**Comment by BentonEdmondson** [comment]
Release `1.2.0` fixes this issue
