### ISSUE TITLE
`stream.dic['Type'] is not LITERAL_XREF` in large file

### ISSUE THREAD

**Issue by traverseda** [BentonEdmondson/knock#40]
```
Traceback (most recent call last):
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 2182, in <module>
    sys.exit(cli_main())
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 2176, in cli_main
    result = decryptBook(userkey, inpath, outpath)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 2146, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1951, in __init__
    parser = PDFParser(doc, inf)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1759, in __init__
    self.doc.set_parser(self)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1384, in set_parser
    self.xrefs = parser.read_xref()
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1886, in read_xref
    self.read_xref_from(pos, xrefs)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1877, in read_xref_from
    self.read_xref_from(pos, xrefs)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1861, in read_xref_from
    xref.load(self)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1316, in load
    stream.dic['Type'] is not LITERAL_XREF:
KeyError: 'Type'
```

The book is a bit of an extreme example, being just under 4000 pages long. You can see it [here](https://archive.org/details/machineryshandbo00ober_611) although you'd need print disabled access in order to download the file.

**Comment by traverseda** [comment]
https://docs.google.com/forms/d/e/1FAIpQLScSBbT17HSQywTm-fQawOK7G4dN-QPbDWNstdfvysoKTXCjKA/viewform

Might be helpful if you or someone you know might be eligible for print disabled access.

**Comment by BentonEdmondson** [comment]
@traverseda try out the latest release and tell me what happens
