### ISSUE TITLE
Crash While Decrypting

### ISSUE THREAD

**Issue by joshuaekingsbury** [BentonEdmondson/knock#42]
I am using the latest release 1.1.0-alpha and have tested with multiple files with the same error occurring each time.

`
./knock ~/Downloads/FILE.acsm 
Received an ACSM (Adobe) file...
Downloading the book from Adobe...

knock> acsmdownloader -d /home/USER/.config/knock/acsm/device.xml -a /home/USER/.config/knock/acsm/activation.xml -k /home/USER/.config/knock/acsm/devicesalt -o /home/USER/Downloads/FILE.drm -f /home/USER/Downloads/FILE.acsm

Created /home/USER/Downloads/FILE.drm

knock[0]>

Decrypting the file...

knock> rmdrm-pdf /home/USER/.config/knock/acsm/activation.xml /home/USER/Downloads/FILE.drm /home/USER/Downloads/FILE.pdf

Traceback (most recent call last):
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 2182, in <module>
    sys.exit(cli_main())
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 2176, in cli_main
    result = decryptBook(userkey, inpath, outpath)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 2146, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1951, in __init__
    parser = PDFParser(doc, inf)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1759, in __init__
    self.doc.set_parser(self)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1384, in set_parser
    self.xrefs = parser.read_xref()
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1886, in read_xref
    self.read_xref_from(pos, xrefs)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1877, in read_xref_from
    self.read_xref_from(pos, xrefs)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1861, in read_xref_from
    xref.load(self)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1316, in load
    stream.dic['Type'] is not LITERAL_XREF:
KeyError: 'Type'

knock[1]>

Error: Command returned error code 1.
`

**Comment by rinseaid** [comment]
@joshuaekingsbury - I see the same issue, but only with .PDF files. EPUB files work ok. I see the same error when I directly run [ineptpdf.py from the noDRM repository](https://github.com/noDRM/DeDRM_tools/blob/master/DeDRM_plugin/ineptpdf.py). 

So it would seem this issue is not specific to knock.

[root@04e1e5eb3831 tmp]# ./ineptpdf.py /config/scripts/ADE_20220117.der /tmp/acsm/test.drm /tmp/acsm/test.pdf
Traceback (most recent call last):
  File "/tmp/./ineptpdf.py", line 2755, in <module>
    sys.exit(cli_main())
  File "/tmp/./ineptpdf.py", line 2624, in cli_main
    result = decryptBook(userkey, inpath, outpath)
  File "/tmp/./ineptpdf.py", line 2591, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "/tmp/./ineptpdf.py", line 2396, in __init__
    parser = PDFParser(doc, inf)
  File "/tmp/./ineptpdf.py", line 2174, in __init__
    self.doc.set_parser(self)
  File "/tmp/./ineptpdf.py", line 1483, in set_parser
    self.xrefs = parser.read_xref()
  File "/tmp/./ineptpdf.py", line 2301, in read_xref
    self.read_xref_from(pos, xrefs)
  File "/tmp/./ineptpdf.py", line 2292, in read_xref_from
    self.read_xref_from(pos, xrefs)
  File "/tmp/./ineptpdf.py", line 2276, in read_xref_from
    xref.load(self)
  File "/tmp/./ineptpdf.py", line 1415, in load
    stream.dic['Type'] is not LITERAL_XREF:
KeyError: 'Type'

**Comment by BentonEdmondson** [comment]
@joshuaekingsbury, @rinseaid try out release `1.2.0` and tell what happens

**Comment by rinseaid** [comment]
@BentonEdmondson, I tested six different ACSM files containing PDFs, and all worked well. knock also starts up much more quickly with your latest optimizations. Very impressive. Thank you!

**Comment by BentonEdmondson** [comment]
Great!
