### ISSUE TITLE
Knock fails to decrypt large PDF: «Ciphertext with incorrect length (not 128 bytes)» when calling PKCS1_v1_5 from within rmdrm-pdf

### ISSUE THREAD

**Issue by simondemeule** [BentonEdmondson/knock#52]
Hi,

I am having a hard type getting a large file (the PDF would be 21.7MB) to un-DRM using knock. My (possibly misguided) Googling suggests this might be because of a limitation within PKCS1_v1_5, which only handles decryption of data up to a certain size; this [StackOverflow](https://stackoverflow.com/questions/55398766/python-pycryptodome-encryption-throws-ciphertext-with-incorrect-length-error) post suggests chopping it up into pieces to get around that. Here is the full console output I get:

```
Received an ACSM (Adobe) file...
Downloading the book from Adobe...

knock> acsmdownloader -d /home/simon/.config/knock/acsm/device.xml -a /home/simon/.config/knock/acsm/activation.xml -k /home/simon/.config/knock/acsm/devicesalt -o /home/simon/krig.drm -f /home/simon/krig.acsm

Created /home/simon/krig.drm

knock[0]>

Decrypting the file...

knock> rmdrm-pdf /home/simon/.config/knock/acsm/activation.xml /home/simon/krig.drm /home/simon/krig.pdf

Traceback (most recent call last):
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 2182, in <module>
    sys.exit(cli_main())
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 2176, in cli_main
    result = decryptBook(userkey, inpath, outpath)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 2146, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1952, in __init__
    doc.initialize(userkey)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1437, in initialize
    return self.initialize_ebx(password, docid, param)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1567, in initialize_ebx
    bookkey = rsa.decrypt(bookkey)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 358, in decrypt
    return _PKCS1_v1_5.new(self._rsa).decrypt(data, 172)
  File "/nix/store/f1a3nmwki356g301z66bv4q49x7j6way-python3.9-pycryptodome-3.11.0/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 174, in decrypt
    raise ValueError("Ciphertext with incorrect length (not %d bytes)" % k)
ValueError: Ciphertext with incorrect length (not 128 bytes)

knock[1]>

Error: Command returned error code 1.
```

This is using the binary release 1.1.0 on Ubuntu 20.04.3 LTS (GNU/Linux 5.13.0-35-generic x86_64).

**Comment by BentonEdmondson** [comment]
@simondemeule try release `1.2.0` and tell me what happens

**Comment by BentonEdmondson** [comment]
Interesting problem. Good chance `1.2.0` resolves it. But without more info I can't help. Feel free to reopen
