### ISSUE TITLE
Unable to decrypt files, only downloads .drm files

### ISSUE THREAD

**Issue by anonygituser** [BentonEdmondson/knock#57]
It downloads the file in drm format but fails to decrypt it. I successfully downloaded a book from the same website few weeks ago, but now it is showing error, from proquest library

```
Received an ACSM (Adobe) file...
Downloading the book from Adobe...

knock> acsmdownloader -d /home/user1/.config/knock/acsm/device.xml -a /home/user1/.config/knock/acsm/activation.xml -k /home/user1/.config/knock/acsm/devicesalt -o /home/user1/Documents/5174948.drm -f /home/user1/Documents/5174948.acsm

Created /home/user1/Documents/5174948.drm

knock[0]>

Decrypting the file...

knock> rmdrm-pdf /home/user1/.config/knock/acsm/activation.xml /home/user1/Documents/5174948.drm /home/user1/Documents/5174948.pdf

Traceback (most recent call last):
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 2182, in <module>
    sys.exit(cli_main())
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 2176, in cli_main
    result = decryptBook(userkey, inpath, outpath)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 2146, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1951, in __init__
    parser = PDFParser(doc, inf)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1759, in __init__
    self.doc.set_parser(self)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1384, in set_parser
    self.xrefs = parser.read_xref()
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1886, in read_xref
    self.read_xref_from(pos, xrefs)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1877, in read_xref_from
    self.read_xref_from(pos, xrefs)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1861, in read_xref_from
    xref.load(self)
  File "/nix/store/srsqqd4s1xgc2r1n9sd7kyr8bn6gbcyz-rmdrm-0.0.0/bin/.rmdrm-pdf-wrapped", line 1316, in load
    stream.dic['Type'] is not LITERAL_XREF:
KeyError: 'Type'

knock[1]>
```

This is using the binary release 1.1.0 on Ubuntu 22.04 LTS

**Comment by BentonEdmondson** [comment]
@anonygituser try release `1.2.0` and tell me what happens

**Comment by anonygituser** [comment]
Here's the command i ran and output.
```
a@a:~$ knock-1.2.0-x86_64-linux ~/Downloads/5174948.acsm 
downloading the file from Adobe...
Download 100%
removing DRM from the file...
error:
Exception code : 0x6006
Message        : Invalid encrypted key size (192). DRM version not supported
```

I am using proquest ebook central library, I downloaded several books from the same website successfully in the past.
If you need i can provide you acsm files.

**Comment by eah13** [comment]
A comment [here; #60](http://www.mobileread.mobi/forums/showthread.php?t=340479&page=6) suggests 192 length keys are not supported by any tool: 

> An encrypted book key of 192 characters means the book is encrypted with the new variant of Adobe's DRM.
>   
>   In 2014 Adobe introduced a new version of their DRM because the old one is so easy to crack. It didn't gain much popularity (because, well, all eReaders would need to be updated to support it), but it looks like some vendors have recently switched to that new version.
>   
>   There is no known public method to remove DRM from these books. One would need to reverse-engineer RMSDK to figure out how this new DRM works.

That error comes from `libgourou`, which bails if the key is > 172.
